import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import worker from '../reactions-service/worker.mjs';
const schema=fs.readFileSync(new URL('../reactions-service/schema.sql',import.meta.url),'utf8');
const origin='https://dantealeks.github.io', work='metafisica/didatico', salt='vPL_7fK2!mQ9#R4xT8@N1zC6pL3wY5sD0', admin='MENSAGENS-CHAVE-2026!rQ7#vL2@xN9pK4sD8';
function setup(){const db=new DatabaseSync(':memory:');db.exec(schema);const env={REACTION_SALT:salt,MESSAGES_ADMIN_KEY:admin,DB:{prepare(query){return{bind(...args){return{first:async()=>db.prepare(query).get(...args)||null,all:async()=>({results:db.prepare(query).all(...args)}),run:async()=>({meta:db.prepare(query).run(...args)})}},first:async()=>db.prepare(query).get()||null,all:async()=>({results:db.prepare(query).all()}),run:async()=>({meta:db.prepare(query).run()})}}}};return {db,env};}
function req(path,body,{auth,ip='192.0.2.8'}={}){return new Request('https://service.workers.dev'+path,{method:body?'POST':'GET',headers:{Origin:origin,'CF-Connecting-IP':ip,...(body?{'Content-Type':'application/json'}:{}),...(auth?{Authorization:'Bearer '+auth}:{})},...(body?{body:JSON.stringify(body)}:{})});}
globalThis.fetch=async()=>Response.json([{id:work,title:'Metafísica',format:'Didático'}]);
test('Health reports only missing configuration names',async()=>{const {db,env}=setup();try{const clean=await worker.fetch(req('/health'),env);assert.equal(clean.status,200);assert.deepEqual((await clean.json()).missing,[]);delete env.DB;const missing=await worker.fetch(req('/health'),env);assert.equal(missing.status,503);assert.deepEqual((await missing.json()).missing,['DB']);}finally{db.close();}});
test('Private message is accepted once and appears only through the admin key',async()=>{const {db,env}=setup();try{const message={work,requestId:'a'.repeat(32),name:'Leitor',email:'leitor@example.com',message:'Minha pergunta é suficientemente detalhada.'};let response=await worker.fetch(req('/messages',message),env);assert.equal(response.status,200);assert.deepEqual(await response.json(),{ok:true});assert.equal(db.prepare('SELECT COUNT(*) AS n FROM private_messages').get().n,1);response=await worker.fetch(req('/messages',message),env);assert.equal(response.status,200);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM private_messages').get().n,1);assert.equal((await worker.fetch(req('/admin/inbox',null,{auth:admin}),env)).status,200);const inbox=await (await worker.fetch(req('/admin/inbox',null,{auth:admin}),env)).json();assert.equal(inbox.items.length,1);assert.equal(inbox.items[0].email,'leitor@example.com');assert.equal(inbox.items[0].message,message.message);assert.equal((await worker.fetch(req('/admin/inbox',null,{auth:'wrong-key'}),env)).status,401);assert.equal((await worker.fetch(req('/messages',{...message,requestId:'f'.repeat(32)},{ip:'198.51.100.3'}),env)).status,200);}finally{db.close();}});
test('Email click is an indicator without reader contact data',async()=>{const {db,env}=setup();try{const response=await worker.fetch(req('/email-click',{work,requestId:'b'.repeat(32)}),env);assert.equal(response.status,200);const row=db.prepare('SELECT kind,name,email,message FROM private_messages').get();assert.equal(row.kind,'email_click');assert.equal(row.name,'');assert.equal(row.email,'');assert.equal(row.message,'');const inbox=await (await worker.fetch(req('/admin/inbox',null,{auth:admin}),env)).json();assert.equal(inbox.items[0].kind,'email_click');}finally{db.close();}});
test('Invalid messages are rejected and public routes cannot read them',async()=>{const {db,env}=setup();try{for(const body of [{work,requestId:'c'.repeat(32),email:'bad',message:'long enough question'}, {work,requestId:'d'.repeat(32),email:'a@b.com',message:'short'}])assert.equal((await worker.fetch(req('/messages',body),env)).status,400);assert.equal((await worker.fetch(req('/private_messages'),env)).status,404);assert.equal((await worker.fetch(req('/admin/inbox'),env)).status,401);}finally{db.close();}});
test('Admin can mark, archive and delete messages',async()=>{const {db,env}=setup();try{await worker.fetch(req('/messages',{work,requestId:'e'.repeat(32),email:'a@example.com',message:'Pergunta de teste longa.'}),env);let inbox=await (await worker.fetch(req('/admin/inbox',null,{auth:admin}),env)).json();const id=inbox.items[0].id;for(const status of ['read','replied','archived']){assert.equal((await worker.fetch(req('/admin/message',{id,status},{auth:admin}),env)).status,200);}assert.equal((await worker.fetch(req('/admin/message',{id,status:'delete'},{auth:admin}),env)).status,200);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM private_messages').get().n,0);}finally{db.close();}});
test('Admin feedback returns public likes and private dislikes for every published text',async()=>{const {db,env}=setup();try{await worker.fetch(req('/vote',{work,voter:'a'.repeat(32),value:'like'}),env);await worker.fetch(req('/vote',{work,voter:'b'.repeat(32),value:'dislike'}),env);const response=await worker.fetch(req('/admin/feedback',null,{auth:admin}),env);assert.equal(response.status,200);const data=await response.json();assert.equal(data.items.length,1);assert.deepEqual(data.items[0],{work,title:'Metafísica',format:'Didático',likes:1,dislikes:1});}finally{db.close();}});
