import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import worker from '../reactions-service/worker.mjs';
const sql=fs.readFileSync(new URL('../reactions-service/schema.sql',import.meta.url),'utf8');
const origin='https://dantealeks.github.io',voter='a'.repeat(32),work='metafisica/didatico';
function setup(){const db=new DatabaseSync(':memory:');db.exec(sql);const env={REACTION_SALT:'s'.repeat(40),DB:{prepare(sql){return {bind(...args){return {async first(){return db.prepare(sql).get(...args)||null;},async run(){return db.prepare(sql).run(...args);}}},async run(){return db.prepare(sql).run();}};}}};return {db,env};}
function req(path,body,extra={}){return new Request('https://service.workers.dev'+path,{method:body?'POST':'GET',headers:{Origin:origin,'CF-Connecting-IP':'192.0.2.1',...(body?{'Content-Type':'application/json'}:{}),...extra},...(body?{body:JSON.stringify(body)}:{})});}
globalThis.fetch=async()=>Response.json([{id:work}]);
test('Likes persist; retries do not duplicate; dislike count stays private; withdrawal works',async()=>{const {db,env}=setup();try{const vote=value=>worker.fetch(req('/vote',{work,voter,value}),env);let r=await vote('like');assert.equal(r.status,200);assert.deepEqual(await r.json(),{likes:1,selection:'like'});await vote('like');assert.equal(db.prepare('SELECT COUNT(*) AS n FROM reactions').get().n,1);r=await vote('dislike');assert.deepEqual(await r.json(),{likes:0,selection:'dislike'});assert.equal(db.prepare('SELECT nao_gostei FROM resumo_avaliacoes').get().nao_gostei,1);assert.deepEqual(await (await worker.fetch(req('/counts?work='+work),env)).json(),{likes:0});r=await vote('none');assert.deepEqual(await r.json(),{likes:0,selection:'none'});assert.equal(db.prepare('SELECT COUNT(*) AS n FROM reactions').get().n,0);}finally{db.close();}});
test('No public route exposes admin data or totals',async()=>{const {db,env}=setup();try{for(const p of ['/admin','/stats','/reactions','/resumo_avaliacoes'])assert.equal((await worker.fetch(req(p),env)).status,404);assert.equal((await worker.fetch(req('/counts?work='+work,null,{Origin:'https://evil.test'}),env)).status,403);}finally{db.close();}});
test('Different browsers count separately and only hashed IDs are stored',async()=>{const {db,env}=setup();try{for(const v of [voter,'b'.repeat(32)])await worker.fetch(req('/vote',{work,voter:v,value:'like'}),env);assert.deepEqual(await (await worker.fetch(req('/counts?work='+work),env)).json(),{likes:2});const ids=db.prepare('SELECT voter FROM reactions').all().map(x=>x.voter);assert(ids.every(x=>x.length===64&&x!==voter));assert(!JSON.stringify(db.prepare('SELECT * FROM rate_limits').all()).includes('192.0.2.1'));}finally{db.close();}});
test('Validation, unknown works, payload bounds and missing configuration fail safely',async()=>{const {db,env}=setup();try{for(const body of [{work,voter,value:'bad'},{work:'../bad',voter,value:'like'},{work,voter:'bad',value:'like'}])assert.equal((await worker.fetch(req('/vote',body),env)).status,400);assert.equal((await worker.fetch(req('/vote',{work:'not-published/didatico',voter,value:'like'}),env)).status,404);assert.equal((await worker.fetch(req('/vote',{work,voter,value:'like',huge:'x'.repeat(2000)}),env)).status,413);assert.equal((await worker.fetch(req('/counts?work='+work),{})).status,503);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM reactions').get().n,0);}finally{db.close();}});
test('Daily rate limit blocks additional writes',async()=>{const {db,env}=setup();try{for(let i=0;i<60;i++)assert.equal((await worker.fetch(req('/vote',{work,voter,value:'like'}),env)).status,200);assert.equal((await worker.fetch(req('/vote',{work,voter,value:'dislike'}),env)).status,429);assert.equal(db.prepare('SELECT value FROM reactions').get().value,'like');}finally{db.close();}});
test('Failure to validate published works prevents writes',async()=>{const {db,env}=setup(),original=globalThis.fetch;try{globalThis.fetch=async()=>{throw Error('network');};assert.equal((await worker.fetch(req('/vote',{work,voter,value:'like'}),env)).status,503);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM reactions').get().n,0);}finally{globalThis.fetch=original;db.close();}});
