// Developer-only DOM tests: NODE_PATH=/path/to/jsdom/node_modules node --test tests/ui.test.cjs
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('jsdom'),M=require('../dist/admin/model.js');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'content/obras.json'),'utf8');
function editor(){const dom=new JSDOM(fs.readFileSync(path.join(root,'dist/admin/index.html'),'utf8'),{url:'https://example.test/Ensaios-Filosoficos/admin/index.html',runScripts:'outside-only'}),w=dom.window;let remote=source,writes=[];w.confirm=()=>true;w.PeregriniEditorGitHub={createClient:()=>({connect:async()=>({text:remote}),reload:async()=>({text:remote}),save:async text=>{writes.push(text);remote=text;},disconnect(){}})};w.PeregriniPublication={digest:async()=>'a'.repeat(64),check:async()=>true};w.HTMLElement.prototype.scrollIntoView=()=>{};for(const f of ['model.js','drafts.js','editor.js'])w.eval(fs.readFileSync(path.join(root,'dist/admin',f),'utf8'));const $=id=>w.document.getElementById(id);async function connect(){await $('connect-form').onsubmit({preventDefault(){},submitter:$('connect-form').querySelector('button')});}function input(id,value){$(id).value=value;$(id).dispatchEvent(new w.Event('input'));}return {dom,w,$,connect,input,writes,setRemote:text=>remote=text};}
test('Editor saves local drafts, recovers them, publishes only on demand and supports a second edit after save',async()=>{const e=editor();try{await e.connect();const initial=e.$('work-title').value;e.input('work-title','Primeira revisão');e.$('draft-save').click();assert.equal(e.writes.length,0);assert(e.w.localStorage.getItem('peregrini:author-draft:v1').includes('Primeira revisão'));e.$('disconnect').click();await e.connect();assert.equal(e.$('draft-recovery').hidden,false);e.$('draft-restore').click();assert.equal(e.$('work-title').value,'Primeira revisão');await e.$('save').onclick();assert.equal(e.writes.length,1);await new Promise(r=>setImmediate(r));assert.match(e.$('publication-state').textContent,/Publicado/);e.input('work-title','Segunda revisão');await e.$('save').onclick();await new Promise(r=>setImmediate(r));assert.equal(JSON.parse(e.writes[1]).works[0].title,'Segunda revisão');assert.equal(e.w.localStorage.getItem('peregrini:author-draft:v1'),null);assert(initial); }finally{e.dom.window.close();}});
test('Draft based on older GitHub catalog cannot overwrite current catalog',async()=>{const e=editor();try{await e.connect();e.input('work-title','Rascunho antigo');e.$('draft-save').click();e.$('disconnect').click();const remote=JSON.parse(source);remote.works[0].title='Mudança em outro aparelho';e.setRemote(JSON.stringify(remote));await e.connect();e.$('draft-restore').click();assert.equal(e.$('work-title').value,'Mudança em outro aparelho');assert.match(e.$('notice').textContent,/bloqueada/);assert(e.$('save').disabled);assert.equal(e.writes.length,0);}finally{e.dom.window.close();}});
test('Unfinished draft survives an empty chapter title; publish validation blocks it',async()=>{const e=editor();try{await e.connect();const id=e.w.document.querySelector('.chapter-editor input').id;e.input(id,'');e.$('draft-save').click();e.$('disconnect').click();await e.connect();e.$('draft-restore').click();assert.equal(e.$(id).value,'');await e.$('save').onclick();assert.match(e.$('notice').textContent,/sem título/);assert.equal(e.writes.length,0);}finally{e.dom.window.close();}});
function memoryDOM(html,url,stored){const dom=new JSDOM(html,{url,runScripts:'outside-only'}),w=dom.window;const key='peregrini:reading:v1:/Ensaios-Filosoficos/';if(stored)w.localStorage.setItem(key,JSON.stringify(stored));Object.defineProperty(w.document,'currentScript',{configurable:true,value:{src:'https://example.test/Ensaios-Filosoficos/reading-memory.js'}});return {dom,w,key,run:()=>w.eval(fs.readFileSync(path.join(root,'dist/reading-memory.js'),'utf8'))};}
test('Home offers a valid saved reading; malicious or missing paths never become links',()=>{const html=fs.readFileSync(path.join(root,'dist/index.html'),'utf8');for(const pathValue of ['obras/metafisica/didatico.html','https://evil.test/','obras/removida/didatico.html']){const m=memoryDOM(html,'https://example.test/Ensaios-Filosoficos/',{path:pathValue,title:'Metafísica',y:900});try{m.run();assert.equal(m.w.document.getElementById('resume-reading').hidden,pathValue!=='obras/metafisica/didatico.html');}finally{m.dom.window.close();}}});
test('Reader remembers position and restores chapter-relative location',()=>{const html=fs.readFileSync(path.join(root,'dist/obras/metafisica/didatico.html'),'utf8'),m=memoryDOM(html,'https://example.test/Ensaios-Filosoficos/obras/metafisica/didatico.html',{path:'obras/metafisica/didatico.html',title:'Metafísica',y:900,chapter:'',offset:0});try{let destination;const chapter=m.w.document.querySelector('.chapter');chapter.getBoundingClientRect=()=>({top:500});Object.defineProperty(chapter,'offsetHeight',{value:1000});const stored=JSON.parse(m.w.localStorage.getItem(m.key));stored.chapter=chapter.id;stored.offset=150;m.w.localStorage.setItem(m.key,JSON.stringify(stored));m.w.scrollTo=options=>destination=options.top;m.run();const box=m.w.document.getElementById('resume-reading');assert.equal(box.hidden,false);box.querySelector('button').click();assert.equal(destination,650);Object.defineProperty(m.w,'scrollY',{value:1500,configurable:true});m.w.dispatchEvent(new m.w.Event('pagehide'));assert.equal(JSON.parse(m.w.localStorage.getItem(m.key)).y,1500);}finally{m.dom.window.close();}});
