import fs from 'node:fs';
import { parseCatalog } from './read-catalog.mjs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const data=parseCatalog(fs.readFileSync(path.join(root,'content/obras.json'),'utf8'));
const E=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formats={sintetico:'Sintético',didatico:'Didático'},statuses={andamento:'Em andamento',finalizado:'Finalizado'},availability={integral:'Texto integral',trecho:'Trecho',demonstracao:'Demonstração'};
const date=d=>d?d.split('-').reverse().join('/'):'Não informada';
const slug=s=>typeof s==='string'&&/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(s);
function ensure(ok,message){if(!ok)throw Error(message);}
ensure(typeof data.author==='string'&&Array.isArray(data.works),'Autor ou lista de obras inválidos');
const ids=new Set();
for(const w of data.works){ensure(slug(w.id)&&!ids.has(w.id),'ID de obra inválido ou repetido: '+w.id);ids.add(w.id);ensure(typeof w.title==='string'&&w.title.trim()&&typeof w.summary==='string'&&typeof w.kind==='string','Título, tipo ou resumo inválido: '+w.id);ensure(Array.isArray(w.variants)&&w.variants.length,'Inclua uma versão: '+w.id);const vs=new Set();for(const v of w.variants){ensure(formats[v.id]&&!vs.has(v.id),'Forma inválida ou repetida: '+w.id);vs.add(v.id);ensure(statuses[v.status]&&availability[v.availability],'Estado ou disponibilidade inválidos: '+w.id);ensure(v.updated===null||(/^\d{4}-\d{2}-\d{2}$/.test(v.updated)&&!isNaN(Date.parse(v.updated))&&new Date(v.updated).toISOString().slice(0,10)===v.updated),'Data inválida: '+w.id);ensure(Array.isArray(v.chapters)&&v.chapters.length,'Inclua capítulos: '+w.id);const sections=new Set();function validate(nodes,depth=0){ensure(depth<=1,'Use capítulos e um nível de subcapítulos');for(const c of nodes){ensure(slug(c.id)&&!sections.has(c.id),'ID de capítulo inválido ou repetido: '+c.id);sections.add(c.id);ensure(typeof c.title==='string'&&c.title.trim()&&Array.isArray(c.paragraphs)&&c.paragraphs.every(p=>typeof p==='string'),'Capítulo inválido: '+c.id);if(c.subchapters){ensure(Array.isArray(c.subchapters),'Subcapítulos inválidos');validate(c.subchapters,depth+1);}}}validate(v.chapters);}}
const href=(w,v,prefix='./')=>`${prefix}obras/${w.id}/${v.id}.html`;
function metadata(v){return `<dl class="work-metadata"><div><dt>Estado</dt><dd>${statuses[v.status]}</dd></div><div><dt>Apresentação</dt><dd>${formats[v.id]}</dd></div><div><dt>Disponível</dt><dd>${availability[v.availability]}</dd></div><div><dt>Última atualização</dt><dd>${date(v.updated)}</dd></div></dl>`;}
function progress(v){return v.status==='andamento'?`<div class="next-grid"><div><small>Última parte escrita</small><strong>${E(v.last||'Não informada')}</strong></div><div><small>Próxima parte</small><strong>${E(v.next||'A definir')}</strong></div></div>`:'';}
function card(w,v){return `<article class="work-card" data-status="${v.status}" data-format="${v.id}"><div class="card-topline"><span>${E(w.kind)}</span><span class="format-badge">${formats[v.id]}</span></div><div class="card-body"><h3><a href="${href(w,v)}">${E(w.title)}</a></h3><p>${E(w.summary)}</p>${metadata(v)}${progress(v)}</div><a class="card-action" href="${href(w,v)}" aria-label="Ler ${E(w.title)}, versão ${formats[v.id]}">Abrir leitura <span aria-hidden="true">↗</span></a></article>`;}
function toc(nodes){return `<ol>${nodes.map(c=>`<li><a href="#${c.id}">${E(c.title)}</a>${c.subchapters?.length?toc(c.subchapters):''}</li>`).join('')}</ol>`;}
function section(c,level=2){return `<section class="chapter" id="${c.id}" tabindex="-1"><h${level}>${E(c.title)}</h${level}>${c.paragraphs.map(p=>`<p>${E(p)}</p>`).join('')}${(c.subchapters||[]).map(s=>section(s,level+1)).join('')}</section>`;}
function page(w,v){return `<!doctype html><html lang="pt-BR" data-theme="luz"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${E(w.title)} · ${formats[v.id]} — Arquivo Peregrini</title><meta name="description" content="${E(w.summary)}"><link rel="stylesheet" href="../../styles.css"><script src="../../preferences.js"></script></head><body class="reading-page"><a class="skip-link" href="#texto">Ir para o texto</a><header class="reading-header"><a class="brand" href="../../index.html#${w.kind==='Suma'?'sumas':'escritos'}"><span class="brand-mark" aria-hidden="true">Ж</span><span>Voltar ao acervo</span></a><a href="#sumario">Sumário</a></header><div class="reading-layout"><aside class="reading-sidebar"><details open id="sumario"><summary>Sumário da obra</summary><nav aria-label="Capítulos e subcapítulos">${toc(v.chapters)}</nav></details><details class="reading-settings" open><summary>Aparência da leitura</summary><label for="reading-size">Tamanho da letra <output id="size-value" for="reading-size">100%</output></label><input id="reading-size" type="range" min="80" max="160" step="10" value="100"><label for="reading-font">Fonte</label><select id="reading-font"><option value="classica">Clássica · Georgia</option><option value="livro">Livro · Palatino</option><option value="simples">Simples · Arial</option></select><label for="reading-theme">Tema</label><select id="reading-theme"><option value="luz">Claro</option><option value="noite">Escuro</option></select><button id="reset-reading" type="button">Restaurar aparência</button></details><button id="print-reading" type="button">Imprimir / salvar como PDF</button><p class="print-help">Na janela de impressão, escolha “Salvar como PDF”.</p></aside><main id="texto" class="reading-text"><header class="work-heading"><p class="eyebrow">${E(w.kind)} · ${formats[v.id]}</p><h1>${E(w.title)}</h1><p class="byline">${E(data.author)}</p><p>${E(w.summary)}</p>${metadata(v)}${v.availability==='demonstracao'?'<p class="demo-notice">Exemplo fictício em latim para demonstrar a leitura.</p>':v.availability==='trecho'?'<p class="demo-notice">Trechos de apresentação. O texto integral ainda não está disponível nesta página.</p>':''}${progress(v)}${w.variants.length>1?`<nav class="version-links" aria-label="Versões da obra"><span>Forma de leitura:</span>${w.variants.map(o=>`<a href="./${o.id}.html" ${o.id===v.id?'aria-current="page"':''}>${formats[o.id]} · ${statuses[o.status]}</a>`).join('')}</nav>`:''}</header>${v.chapters.map(c=>section(c)).join('')}</main></div><script src="../../reader.js"></script></body></html>`;}
// Validate the entire catalog before replacing any generated pages.
const target=path.join(root,'dist/obras');fs.mkdirSync(target,{recursive:true});
const expected=new Set();for(const w of data.works){fs.mkdirSync(path.join(target,w.id),{recursive:true});for(const v of w.variants){const file=path.join(target,w.id,`${v.id}.html`);expected.add(file);fs.writeFileSync(file,page(w,v));}}
for(const dir of fs.readdirSync(target,{withFileTypes:true})){if(!dir.isDirectory())continue;for(const name of fs.readdirSync(path.join(target,dir.name))){const f=path.join(target,dir.name,name);if(name.endsWith('.html')&&!expected.has(f))fs.unlinkSync(f);}}
const cards=kind=>data.works.filter(w=>(w.kind==='Suma')===kind).flatMap(w=>w.variants.map(v=>card(w,v))).join('\n');
let home=fs.readFileSync(path.join(root,'templates/home.html'),'utf8').replace('{{WORKS}}',cards(false)).replace('{{SUMAS}}',cards(true));fs.writeFileSync(path.join(root,'dist/index.html'),home);
console.log(`Acervo gerado: ${data.works.length} obras, ${expected.size} páginas de leitura.`);

